preprocess:
   window: 1200
   overlap: 600
train_test_evaluate:
   window: 1200
   overlap: 600
   epochs: 1
   dropout_rate: 0.01
   learning_rate: 0.01
   num_cell_dense1: 32
   num_cell_lstm1: 32
   num_cell_lstm2: 32
   num_cell_lstm3: 32
   train_subjects: "0-1-2-3"
   validation_subjects: "4"
   test_subjects: "5-6"
   accuracy_thresold: 0.1
   environment: "development"

