apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-node
  template:
    metadata:
      labels:
        app: main-node
    spec:
      containers:
        - name: main-node
          image: main-image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080