apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staging-node
  template:
    metadata:
      labels:
        app: staging-node
    spec:
      containers:
        - name: staging-node
          image: staging-image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080