apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- staging-deployment.yaml
- staging-service.yaml

images:
- name: staging-image
  newName: 424710357996.dkr.ecr.us-east-2.amazonaws.com/rnn-model-image
  newTag: 79bd671eff244c36141680be3063440f3732b8dc