# build.yml
on:
  push:
    branches:
      - development
      - main
      - staging
# schedule:
#    - cron:  '* * 1 * *' # Run the pipeline one time a day

name: OpenSource Stack Ci/Cd

env:
 AWS_DEFAULT_REGION: us-east-2
 AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 IMAGE_NAME: rnn-model-image
 PYTHON_VERSION: 3.8
 INPUT_DATA: s3://opensource-stack-input-data/PPG_ACC_dataset

jobs: 
  run_cicd:
    name: "Run Ci/Cd"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Get the current branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: myref      

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      - name: Configure pipeline parameters
        run: |
          cp params.yaml copy_params.yaml
          sed -i 's/"environment-replace"/"${{ steps.myref.outputs.branch }}"/' params.yaml
      - name: Pull latest data
        run: |
          cd data/
          dvc import-url ${{ env.INPUT_DATA }}
          ls .
      - name: Execute DVC pipeline
        run: |
          dvc repro -f
          echo $(cat pipeline/artifact_location.txt)
      - name: Push latest data to remote
        run: |
          rm params.yaml
          mv copy_params.yaml params.yaml
          dvc push

      - name: Commit new data
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add data/PPG_ACC_dataset.dvc
            git commit -a -m "${{ github.sha }}"
      - name: Push changes to current branch
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ steps.myref.outputs.branch }}
            force: true  
          
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Update MLFlow docker file
        run: |
          sed -i 's#nginx_file#https://raw.githubusercontent.com/RomainCapo/OpenSource-HAR/${{ steps.myref.outputs.branch }}/monitoring/nginx.conf#' monitoring/docker_utils.py
          rm /opt/hostedtoolcache/Python/$(ls /opt/hostedtoolcache/Python/ | grep ^${{ env.PYTHON_VERSION }})/x64/lib/python${{ env.PYTHON_VERSION }}/site-packages/mlflow/models/docker_utils.py
          cp monitoring/docker_utils.py /opt/hostedtoolcache/Python/$(ls /opt/hostedtoolcache/Python/ | grep ^${{ env.PYTHON_VERSION }})/x64/lib/python${{ env.PYTHON_VERSION }}/site-packages/mlflow/models/docker_utils.py
      - name: Build Docker image
        run : |
          mlflow models build-docker -m "$(cat pipeline/artifact_location.txt)" -n "$IMAGE_NAME:${{ steps.myref.outputs.branch }}_${{ github.sha }}"
      - name: Tag image
        run: |
          docker tag $IMAGE_NAME:${{ steps.myref.outputs.branch }}_${{ github.sha }} $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME:${{ steps.myref.outputs.branch }}_${{ github.sha }}
      - name: Push Docker image to ECR
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME:${{ steps.myref.outputs.branch }}_${{ github.sha }}
          
      - name: Set image tag
        run: |
            cd deploy/${{ steps.myref.outputs.branch }}
            kustomize edit set image ${{ steps.myref.outputs.branch }}-image=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME:${{ steps.myref.outputs.branch }}_${{ github.sha }}
            cat kustomization.yaml   
          
      - name: Install eksctl
        run: |
         curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
         sudo mv /tmp/eksctl /usr/local/bin
         . <(eksctl completion bash)
      - name: Connect to cluster
        run: |
          eksctl utils write-kubeconfig --cluster=opensource-stack
      - name: Apply new config
        run: |
          cd deploy/${{ steps.myref.outputs.branch }}
          kustomize build | kubectl replace --force -f -
          
