# build.yml
on:
  pull_request:
    branches:        
    - main        
  push:
    branches:
    - main

name: OpenSource Stack Ci/Cd

env:
 AWS_DEFAULT_REGION: us-east-2
 AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 GITHUB_BRANCH: ${{ github.ref }}
 IMAGE_NAME: rnn-model-image:${GITHUB_BRANCH##*/}_${{ github.sha }} 
 PYTHON_VERSION: 3.8.12

jobs: 
  run_cicd:
    name: "Run Ci/Cd"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: PYTHON_VERSION
      - name: Get the current branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: myref      

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[s3]

      - name: Test
        run: |
          ls /opt/hostedtoolcache/Python/$(ls /opt/hostedtoolcache/ | grep $PYTHON_VERSION )
         
  
