# build.yml
on:
  pull_request:
    branches:        
    - main        
  push:
    branches:
    - main

name: OpenSource Stack Ci/Cd

env:
 AWS_DEFAULT_REGION: us-east-2
 AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 IMAGE_NAME: rnn-model-image:${{ github.sha }}

jobs: 
  run_cicd:
    name: "Run Ci/Cd"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: 3.8
      - name: Install eksctl
        run: |
         curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
         sudo mv /tmp/eksctl /usr/local/bin
         . <(eksctl completion bash)
      - name: Connect to cluster
        run: |
          eksctl utils write-kubeconfig --cluster=opensource-stack-cluster
      - name: Apply new config
        run: |
          kubectl get pods -A
          
