# build.yml
on:
  pull_request:
    branches:        
    - main
    - staging
    - development        
  push:
    branches:
    - main
    - staging
    - development

name: OpenSource Stack Ci/Cd

env:
 AWS_DEFAULT_REGION: us-east-2
 AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 GITHUB_REF: ${{ github.ref }}
 GITHUB_BRANCH: ${GITHUB_REF##*/}
 IMAGE_NAME: rnn-model-image:${GITHUB_BRANCH}_${{ github.sha }} 
 PYTHON_VERSION: 3.8

jobs: 
  run_cicd:
    name: "Run Ci/Cd"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: ${{ env.PYTHON_VERSION}}

      - name: Install Python dependencies
        run: |
          sed -i 's/"environment-replace"/"$GIT_BRANCH"/' params.yaml
        env: 
          GIT_BRANCH: ${{ env.GITHUB_BRANCH }}

